server:
  servlet:
    context-path: /api
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: manageradmin
    password: 1234567890
    druid:
      # druid连接池监控
      stat-view-servlet.login-username: manager
      stat-view-servlet.login-password: manager_server2018
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  servlet:
    multipart:
      max-request-size: 10Mb
      max-file-size: 2Mb
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    default-encoding: UTF-8

manage:
  fileType: .jpg,.png,.gif,.tif,.psd,.dng.,cr2,.nef
  files:
    path: /Users/alex/program/IdeaProjects/manage
  mail:
    to: xxx@gmail.com
  img:
    filePath: /Users/alex/Downloads